### ISSUE TITLE
Question: Product assets export

### ISSUE THREAD

**Issue by jeroenslor** [episerver/Quicksilver#1]
Hi,

On the following code line you are importing product assets. How did you manage to export the assets from epi?

https://github.com/episerver/Quicksilver/blob/72edc555a09e1bfa33e014eb353fa39e3232f4f9/Sources/EPiServer.Reference.Commerce.Site/Infrastructure/ImportSiteContent.cs#L59

**Comment by quanmaiepi** [comment]
Hi,
We have a small tool to do that. Basically it’s an aspx file which needs to be copied to website root folder and run.

<%@ Page Language="C#" AutoEventWireup="true" Inherits="System.Web.UI.Page" %>
<%@ Import Namespace="System.IO" %>
<%@ Import Namespace="EPiServer" %>
<%@ Import Namespace="EPiServer.Core" %>
<%@ Import Namespace="EPiServer.Core.Transfer" %>
<%@ Import Namespace="EPiServer.DataAbstraction" %>
<%@ Import Namespace="EPiServer.DataAccess" %>
<%@ Import Namespace="EPiServer.Enterprise" %>
<%@ Import Namespace="EPiServer.Implementation" %>
<%@ Import Namespace="EPiServer.ServiceLocation" %>
<%@ Import Namespace="EPiServer.Personalization.VisitorGroups" %>
<%@ Import Namespace="EPiServer.Framework.Cache" %>
<%@ Import Namespace="EPiServer.Framework.Blobs" %>

<script runat="server">
    private Injected<ITabDefinitionRepository> _tabDefinitionRepository;
    private Injected<IPropertyDefinitionRepository> _propertyDefinitionRepository;
    private Injected<ContentListDB> _contentListDB;
    private static IContentRepository _contentRepository = ServiceLocator.Current.GetInstance<IContentRepository>();
    private static DecoratedClassFactory CreateClassFactory(string type, string id)
    {
        Type concreteType = Type.GetType(type, true);
        return Activator.CreateInstance(concreteType, new Object[] { id }) as DecoratedClassFactory;
    }
    private static void WriteError(System.Web.HttpResponse response, string errorMessage)
    {
        response.Clear();
        response.Write("<span style=\"color: red;\">Error: " + errorMessage + "</span><br />");
        response.End();
    }
    private void Page_Load(object sender, System.EventArgs e)
    {
        DataExporter exporter = new DataExporter();
        //Get all page references and data
        List<PageReference> startPageReferenceList = new List<PageReference>();
        List<ContentData> startPageDataList = new List<ContentData>();
        ContentFolder rootFolder = _contentRepository.GetChildren<ContentFolder>(EPiServer.Web.SiteDefinition.Current.GlobalAssetsRoot).FirstOrDefault() as ContentFolder;
        exporter.Frames.AddRange(Frame.List());
        exporter.TabDefinitions.AddRange(_tabDefinitionRepository.Service.List());
        foreach (var propertyDefinition in _propertyDefinitionRepository.Service.ListDynamic())
        {
            exporter.DynamicPropertyDefinitions.Add(propertyDefinition);
        }
        exporter.Categories.AddRange(Category.GetRoot().Categories);
        //Set rootFolder to exporter
        ExportSource sourceRoot = new ExportSource(rootFolder.ContentLink, EPiServer.Core.Transfer.ExportSource.RecursiveLevelInfinity);
        exporter.SourceRoots.Add(sourceRoot);
        //property settings
        exporter.ExportPropertySettings = true;
        exporter.IncludeImplicitContentDependencies = true;
        if (Request.QueryString["debug"] != null)
        {
            Response.Clear();
            exporter.Stream = new MemoryStream();
            exporter.Export();
            if (exporter.Log.Errors.Count > 0)
            {
                foreach (string s in exporter.Log.Errors)
                {
                    Response.Write(s + "<br>");
                }
            }
            else
            {
                Response.Write("OK");
            }
        }
        else
        {
            Response.Clear();
            string file = Path.GetTempFileName();
            exporter.Stream = new FileStream(file, FileMode.OpenOrCreate, FileAccess.Write | FileAccess.Read, FileShare.Read);
            exporter.Export();
            exporter.Close();
            if (exporter.Log.Errors.Count > 0)
            {
                throw new Exception("errors occured,try &debug=true");
            }
            Response.ContentType = "binary/octet-stream";
            Response.AddHeader("Content-disposition", "attachment; filename=CatalogAssets.episerverdata");
            exporter.Stream.Close();
            Response.WriteFile(file);
        }
        Response.End();
    }
</script>

**Comment by jeroenslor** [comment]
Great thanks, and how do you export the relations between exported catalog and exported assets?

**Comment by lunchin** [comment]
This happens automatically if exporting catalog from front end site.  COmmerce manager does not have the models available for the media so it can not create the asset relations.  Here is the coe to export site from front end site,

protected void Page_Load(object sender, EventArgs e)
        {
            var catalogOutputName = String.Format("CatalogExport_{0}_{1}", "Fashion", DateTime.Now.ToString("yyyyMMdd-HHmmss"));
            var dirName = Path.GetTempPath() + catalogOutputName;
            if (Directory.Exists(dirName))
            {
                Directory.Delete(dirName, true);
            }
            var dir = Directory.CreateDirectory(dirName);
            var filePath = dir.FullName + "\Catalog.xml";
            using (var fs = new FileStream(filePath, FileMode.Create, FileAccess.ReadWrite))
            {
                new CatalogImportExport().Export("Fashion", fs, dir.FullName);
                fs.Close();
                ZipHelper.CreateZip(dir.FullName, String.Concat(dir.FullName, ".zip"));
            }
            if (!String.IsNullOrEmpty(String.Concat(dir.FullName, ".zip")))
            {
                Response.ClearContent();
                Response.Clear();
                Response.ContentType = "application/octet-stream";
                Response.AddHeader("Content-Disposition", "attachment; filename=" + catalogOutputName + ".zip;");
                Response.TransmitFile(String.Concat(dir.FullName, ".zip"));
                Response.Flush();
                Response.End();
            }
        }

**Comment by jeroenslor** [comment]
Exactly what I needed, thanks!
