### ISSUE TITLE
GetMockOrder in ConfirmationService not returning PurchaseOrder correctly

### ISSUE THREAD

**Issue by MEmanuelsson** [episerver/Quicksilver#10]
When looking at the order confirmation page in edit-mode, a purchase order is not correctly retrieved from the function GetMockOrder if there exists a shopping cart with a higher Total than the Total of all the purchase orders. The line of code causing this error seems to be this one:

SqlMetaWhereClause = "[ObjectId] = (SELECT TOP 1 OrderGroupId FROM OrderGroup order by Total desc)"

**Comment by magnusstrale** [comment]
Hi,

This has been fixed in Quicksilver 2.0 (currently on develop, shortly on the master branch as well). When viewed in edit mode it will simply fake a dummy order rather than retrieving something from the database.

**Comment by maxmakisalo** [comment]
Just out of curiosity, 2.0 development is not done in development branch?

**Comment by mrahl** [comment]
@maxmakisalo no, it is developed as part of the Commerce platform development, exported through a series of transformation steps (for example replacing project references with NuGet references) and then pushed to GitHub.
