### ISSUE TITLE
Commerce Manager access (permissions to functions) on Identity users

### ISSUE THREAD

**Issue by Hyzac** [episerver/Quicksilver#11]
Created a user which is part of the Administrators and WebAdmins groups but in Commerce manager it only states Access denied. The admin user is the only one which is working in CM. How to manage Commerce manager access to new users with Identity provider?

**Comment by mrahl** [comment]
Is there any guidance to find in the responses to [Issue 7](https://github.com/episerver/Quicksilver/issues/7) and [Issue 8](https://github.com/episerver/Quicksilver/issues/8)?

**Comment by Hyzac** [comment]
No not really. I have this setup and can create users based on the Identity provider. But when creating a user that has the same groups setup as the admin user (WebAdmins and Administrators) I still get the access denied in Commerce manager. The permissions to functions is already setup allowing WebAdmins and Administrators access to most of the functions but it seems there is some level of access setting that I cannot find or set.

**Comment by magnusstrale** [comment]
This will be fixed by COM-1553 (see http://world.episerver.com/support/Bug-list/bug/COM-1553 )

**Comment by magnusstrale** [comment]
We now have a major update for Quicksilver (supporting new promotion system - currently on develop branch, shortly on master) but the fix for COM-1553 is unfortunately not in there. We hope to be able to fix it in the near future.

**Comment by magnusstrale** [comment]
Since COM-1553 has been closed I'm closing this issue now.
