### ISSUE TITLE
PaymentmethodId doesn't change

### ISSUE THREAD

**Issue by Hyzac** [episerver/Quicksilver#12]
If you haven't noticed it yet the id for the payment always is the first selected and cannot be changed with the current setup. Since the form is serialized and sent in before the new selected payment has had the chance to render it's specific id, the information sent in paymentViewModel to the Update method of the Checkout Controller is always the first one. This results in that the new payment is created with wrong payment method id and this causes issues if you later want to get hold of the correct payment based on the method Id.

**Comment by Hyzac** [comment]
The immidiate solution for it I found was to add a data-id property to the radiobuttons for payment and set the value of those to each specific id. Then in checkout.js changePayment method do this before the form is serialized and sent:
`var checkedValue = $('input[name="SystemName"]:checked').data('id');
        $('input[name="PaymentMethod.PaymentMethodId"]').val(checkedValue);`

**Comment by magnusstrale** [comment]
Apologies for the slow response - this is one of the things that should be fixed in the soon-to-come major update that will use the new promotion system in Episerver Commerce.

**Comment by magnusstrale** [comment]
Hi,

This should now be fixed - major update on develop branch, soon on master.
