### ISSUE TITLE
A socket operation was attempted to an unreachable host

### ISSUE THREAD

**Issue by sandeepsahoogirik** [episerver/Quicksilver#16]
Hi
When I run the project the first time after installing the db script I get the error

A socket operation was attempted to an unreachable host

any ideas why this would be

Kind Regards
Sandeep

**Comment by quanmaiepi** [comment]
Hi,
What is the full stacktrace of the error?

**Comment by magnusstrale** [comment]
If you're running without a wired network connection this can happen. Check your web.config file and remove all entries related to EventReplication endpoints. I e kill the following lines

```
    <endpoint name="RemoteEventServiceEndPoint" contract="EPiServer.Events.ServiceModel.IEventReplication" binding="customBinding" bindingConfiguration="RemoteEventsBinding" address="soap.udp://239.255.255.19:5000/RemoteEventService" />
```

...and...

```
  <endpoint name="RemoteEventServiceClientEndPoint" address="soap.udp://239.255.255.19:5000/RemoteEventService" binding="customBinding" bindingConfiguration="RemoteEventsBinding" contract="EPiServer.Events.ServiceModel.IEventReplication" />
```

**Comment by sandeepsahoogirik** [comment]
Hi Magnusstrale 

Thanks for you input. Commenting the two lines from the config made it to work.  Really appreciate the input. Is there anything specific it is used for in the demo site?

Thanks 
Kind Regards
Sandeep

**Comment by magnusstrale** [comment]
The remote event system is used to send cache removal events across the network. It is only needed if you run multiple machines (front-ends) against the same database. I e for development purposes you'll be fine without it.

**Comment by quanmaiepi** [comment]
It's in the standard installation of Commerce - it's for remote events so Commerce Manager site can "communicate" with front-end site. For example, when you update an entry in CM, it will fire events to let front-end site (in this case, quicksilver) to know that entry was updated, then it'll clear cache and such.

**Comment by sandeepsahoogirik** [comment]
Thanks Again
Much appreciate the quick response. 
Kind Regards
Sandeep
