### ISSUE TITLE
Nuget Package Upgrade - '404 Not Found'

### ISSUE THREAD

**Issue by anjumrizwi** [episerver/Quicksilver#17]
I am facing build issue. Below is the step what I have done.

1. I downloaded the latest code from master branch. 
2. Build successfully.
3. I try to Install EPIServer.Mail.
 
Need help please. I tried too many alternate way nut all in vain. 

Attempting to gather dependency information for package 'EPiServer.Mail.8.0.0.33' with respect to project 'EPiServer.Reference.Commerce.Site', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 1.41 min
Attempting to resolve dependencies for package 'EPiServer.Mail.8.0.0.33' with DependencyBehavior 'Lowest'
Unable to find a version of 'EPiServer.CMS.Core' that is compatible with 'EPiServer.Mail 8.0.0.33 constraint: EPiServer.CMS.Core (>= 9.0.0 && < 10.0.0)'.

I tried to upgrade the other package then I got below issue
Resolved actions to install package 'EPiServer.CMS.Core.10.1.0'
The V2 feed at 'https://nuget.episerver.com/FindPackagesById()?id='EPiServer.CMS.Core'' returned an unexpected status code '404 Not Found'.

**Comment by quanmaiepi** [comment]
QS 2.0 is  CMS-10 compatible, while there is no EPiServer.Mail package which is CMS-10 compatible. You will have to wait until we release a CMS-10 compatible Mail package (which is unlikely, IMO), or use previous version of QS which did not require CMS-10
