### ISSUE TITLE
Unable To Add EPiServer.ServiceApi

### ISSUE THREAD

**Issue by jon419** [episerver/Quicksilver#2]
When you try to add the nuget package EPiServer.ServiceApi you get the following nuget error:

Attempting to resolve dependency 'EPiServer.Cms.Core (≥ 8.1.0 && < 9.0)'.Attempting to resolve dependency 'EPiServer.Framework (= 8.9.0)'.Attempting to resolve dependency 'Newtonsoft.Json (≥ 5.0.8 && < 7.0)'.Attempting to resolve dependency 'Microsoft.AspNet.Mvc (≥ 4.0.20710.0 && < 6.0)'.Attempting to resolve dependency 'Microsoft.AspNet.WebPages (≥ 3.2.3 && < 3.3.0)'.Attempting to resolve dependency 'Microsoft.Web.Infrastructure (≥ 1.0.0.0)'.Attempting to resolve dependency 'Microsoft.AspNet.Razor (≥ 3.2.3 && < 3.3.0)'.Attempting to resolve dependency 'structuremap (≥ 2.6.4.1 && < 3.0)'.Attempting to resolve dependency 'EPiServer.Logging.Log4Net (≥ 1.0 && < 2.0)'.Attempting to resolve dependency 'log4net (= 1.2.10)'.Attempting to resolve dependency 'Castle.Windsor (≥ 3.2 && < 4.0)'.Attempting to resolve dependency 'Castle.Core (≥ 3.3.0)'.Attempting to resolve dependency 'Owin (≥ 1.0 && < 2.0)'.Attempting to resolve dependency 'System.IdentityModel.Tokens.Jwt (≥ 3.0 && < 5.0)'.Attempting to resolve dependency 'Microsoft.AspNet.WebApi (≥ 5.1.2 && < 6.0)'.Attempting to resolve dependency 'Microsoft.AspNet.WebApi.WebHost (≥ 5.2.3 && < 5.3.0)'.Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Core (≥ 5.2.3 && < 5.3.0)'.Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Client (≥ 5.2.3)'.Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Owin (≥ 5.1.2 && < 6.0)'.Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Core (≥ 5.1.2 && < 5.2.0)'.Updating 'Microsoft.AspNet.WebApi.Core 5.2.3' to 'Microsoft.AspNet.WebApi.Core 5.1.2' failed. Unable to find a version of 'Microsoft.AspNet.WebApi.WebHost' that is compatible with 'Microsoft.AspNet.WebApi.Core 5.1.2'.

**Comment by magnusstrale** [comment]
Hi,

Looks like the version range for the Service API dependencies needs to be tweaked. Fortunately enough the Service API is owned by our team. I will raise a bug for the Service API and get back here as soon as we've verified the problem.

**Comment by magnusstrale** [comment]
Hi,

We decided to fix the problem by adding a reference to the Quicksilver site which will make sure that the NuGet version resolution heuristics will be able to find the correct version of the package.

I expect we will push updates to the develop branch later today or possibly on Monday, after that there will be some bugfixing before we merge to master, which we'll use as the stable branch.

**Comment by jon419** [comment]
I look forward to the update.  The reason I am inquiring about this is that I ended up in basically the same situation on our commerce project for our client.  Someone mentioned I try it out on Quicksilver and I noticed the issue here too.

**Comment by jon419** [comment]
Any change on this?  I see the dependencies on the nuget packages for ServiceApi haven't changed yet.

**Comment by quanmaiepi** [comment]
Hi,
Did you try with develop branch?

**Comment by jon419** [comment]
Yes:

Attempting to resolve dependency 'EPiServer.ServiceApi (≥ 1.5.2)'.
Attempting to resolve dependency 'EPiServer.Cms.Core (≥ 8.1.0 && < 9.0)'.
Attempting to resolve dependency 'EPiServer.Framework (= 8.10.0)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 5.0.8 && < 7.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.Mvc (≥ 4.0.20710.0 && < 6.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebPages (≥ 3.2.3 && < 3.3.0)'.
Attempting to resolve dependency 'Microsoft.Web.Infrastructure (≥ 1.0.0.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.Razor (≥ 3.2.3 && < 3.3.0)'.
Attempting to resolve dependency 'structuremap (≥ 2.6.4.1 && < 3.0)'.
Attempting to resolve dependency 'EPiServer.Logging.Log4Net (≥ 1.0 && < 2.0)'.
Attempting to resolve dependency 'log4net (= 1.2.10)'.
Attempting to resolve dependency 'Castle.Windsor (≥ 3.2 && < 4.0)'.
Attempting to resolve dependency 'Castle.Core (≥ 3.3.0)'.
Attempting to resolve dependency 'Owin (≥ 1.0 && < 2.0)'.
Attempting to resolve dependency 'System.IdentityModel.Tokens.Jwt (≥ 3.0 && < 5.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebApi (≥ 5.1.2 && < 6.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.WebHost (≥ 5.2.3 && < 5.3.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Core (≥ 5.2.3 && < 5.3.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Client (≥ 5.2.3)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Owin (≥ 5.1.2 && < 6.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Core (≥ 5.1.2 && < 5.2.0)'.
Updating 'Microsoft.AspNet.WebApi.Core 5.2.3' to 'Microsoft.AspNet.WebApi.Core 5.1.2' failed. Unable to find a version of 'Microsoft.AspNet.WebApi.WebHost' that is compatible with 'Microsoft.AspNet.WebApi.Core 5.1.2'.

**Comment by gonzalo-g** [comment]
We're on it. It should be fixed in the next version pushed on develop.

**Comment by JohanHedberg** [comment]
@jon419: Our fix is now available on the develop branch. Pull the latest Changes from it and you should be able to install your packages now.

**Comment by magnusstrale** [comment]
...and the fix has been on the master branch for some time now as well. Will close this issue now - feel free to open a new issue if you're still having problems.
