### ISSUE TITLE
Getting Type mismatch exception

### ISSUE THREAD

**Issue by mobad6** [episerver/Quicksilver#26]
getting error:
An exception of type 'EPiServer.Core.TypeMismatchException' occurred in EPiServer.dll but was not handled in user code

Additional information: Content with id '5' is of type 'EPiServer.Core.PageData' which does not inherit required type 'EPiServer.Reference.Commerce.Site.Features.Start.Pages.StartPage'

in LoginController.cs file , line #66:
StartPage startPage = _contentLoader.Get<StartPage>(ContentReference.StartPage);

**Comment by quanmaiepi** [comment]
Sorry for a very late reply, but it seems to me that that the data was not properly imported. In this case I'd suggest to recreate the databases (rerun setupdatabases.cmd), and let the migration step does it job.
