### ISSUE TITLE
unable to login episerver commerce

### ISSUE THREAD

**Issue by asanthosh69** [episerver/Quicksilver#28]
![image](https://user-images.githubusercontent.com/26564920/39581211-ad19b3da-4f08-11e8-9f12-1441564f4f4f.png)

I am unable to login quick sliver commerce site,can any one share the credentials

**Comment by pergunsarfs** [comment]
It should be admin@example.com/store.

See "Installation" step 5, https://github.com/episerver/Quicksilver/blob/master/README.md.
