### ISSUE TITLE
Solution uses EPiServer.CMS version 11.5.1, which is not available via NuGet

### ISSUE THREAD

**Issue by DrewNull** [episerver/Quicksilver#29]
I happened to pull this down today and noticed that the 11.5.1 package versions are not available on NuGet. So, when you attempt to build the solution, you get a NuGet package restore error. I was able to get around this by first running SetupDatabases.cmd and then manually updating each project's package.config. But the repo should probably be updated to use 11.5.4 (latest stable as of this writing). Just a heads up. Thanks!

**Comment by mrahl** [comment]
Seems there was a mistake publishing packages for the 11.5.1 version, the EPiServer.CMS package should have been published as well. I will make sure it is. Thanks for notifying us!
