### ISSUE TITLE
First run error: There is no contentType registered for: EPiServer.Commerce.Marketing.SalesCampaignFolder

### ISSUE THREAD

**Issue by bbsdddougla** [episerver/Quicksilver#32]
I followed the steps to setup the project
- Clone
- Add the nuget feed
- Restore packages
- Build
- Create the database.

When running from Visual Studio I get the following error message on a 500 page with stack traces:
`There is no contentType registered for: EPiServer.Commerce.Marketing.SalesCampaignFolder.`

the error occurrs in 

`EPiServer.Commerce.Initialization.InitializationModule.RegisterContentRoots(InitializationEngine context)`

Stopping the site and restarting it seems to fix the problem.

**Comment by vietanh-optimizely** [comment]
Hi,
I can not reproduce the issue. We (dev team) noted and will keep an eye on this case.

Regards,
Viet Anh

**Comment by bbsdddougla** [comment]
@vietanh-epi 
Thanks for checking. If I can, I'll try once more to reproduce.
-Drew

**Comment by marisks** [comment]
I have the same issue with the latest version.

**Comment by quanmaiepi** [comment]
@marisks if you recreate the db, does the problem still persist?

**Comment by marisks** [comment]
Just recreated and still the same issue.

**Comment by quanmaiepi** [comment]
That is indeed strange. Can you zip the solution and the databases and send to us?

**Comment by marisks** [comment]
Here is the link: https://drive.google.com/file/d/1ABRncpAYbd5Rpy2WIwwgXBv_VRWjLYTl/view?usp=sharing

Backups are in the root folder Backups.zip.

**Comment by quanmaiepi** [comment]
Thanks, we will look into it as soon as time permits
