### ISSUE TITLE
Hover on admin list item

### ISSUE THREAD

**Issue by is-it-alex** [episerver/Quicksilver#36]
Hi!
Could you possibly add hover on active admin list item? Even with adding "epi-navigation-selected" class to li it looks much better(and informative, that important when you have a lot of items in a list). [example](https://i.paste.pics/9df5ebfe5c80466e2d27b8ee1ab0790f.png)

**Comment by quanmaiepi** [comment]
This is unfortunately out of scope for this repository (which is Quicksilver-focused)
