### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by javafun** [episerver/Quicksilver#37]
Hi 

I follow the readme instruction to build styling and find out the **BuildLessFiles** target no longer exist in the Site project. I then trace back to the history and confirm it's been removed from 12.3.0. 

Does Episerver intentionally remove this from the project? If yes, can you please update the readme so it won't confuse other in the future?

Thanks

**Comment by wojciechGabelBright** [comment]
For anyone struggling with this:
1. Instal node.js 
2. Install less `lpm install less -g`
3. compile less file with : `lessc Styles/style.less > Styles/style.css` in Site folder
