### ISSUE TITLE
Episerver.Tracking.Core 1.8.0 is not available

### ISSUE THREAD

**Issue by ChazKlein** [episerver/Quicksilver#38]
Seems like the Tracking.commerce and Personalization.commerce are both dependent on it being 1.8 which is not available. Downgrading to 1.7.2 then causes those dependencies to break and if I downgrade those as well then the site still won't build. Any suggestions?

**Comment by quanmaiepi** [comment]
Hi, we are aware of the problem. Tracking.Core 1.8.0 will be published next week. Thank you for your patience and apologies for the inconveniences.

**Comment by ChazKlein** [comment]
Great thanks; I'll keep an eye out for the new version to be released.
