### ISSUE TITLE
Build project and having Login failed issue 

### ISSUE THREAD

**Issue by vutung3196** [episerver/Quicksilver#43]
Hi there,
I have cloned codes and followed all steps in Readme, but when building the project, I got login failed issue which is described in the attached image below. 
![image](https://user-images.githubusercontent.com/24209332/66180845-b81f7e80-e698-11e9-96e7-ab111aa9743d.png)
Please help me fix that issue.
Thank you so much

**Comment by vietanh-optimizely** [comment]
Hi,

I guess you cloned the latest Quicksilver version (13.7.1).
Can you access the Commerce databases using the Quicksilver account?
Username: Quicksilver
Password: Episerver15

Regards
/Viet-Anh

**Comment by vutung3196** [comment]
Hi @vietanh-epi , I'm not sure that I need to access to Commerce databse, I have run SetupDatabases.cmd, and I'm still having this issue.

**Comment by vutung3196** [comment]
Hi @vietanh-epi , I have access to Episerver database by using QuickSilver account. 
![image](https://user-images.githubusercontent.com/24209332/66186552-beb7f100-e6ac-11e9-8074-858165abb280.png)

**Comment by vutung3196** [comment]
The issue has been fixed, I just forgot to enable sql server authentication mode in sql server instance. It has been fixed by selecting **SQL Server and Windows Authentication mode**. I'm happy to close this issue.

**Comment by vietanh-optimizely** [comment]
> Hi,
> 
> I guess you cloned the latest Quicksilver version (13.7.1).
> Can you access the Commerce databases using the Quicksilver account?
> Username: Quicksilver
> Password: Episerver15
> 
> Regards
> /Viet-Anh

Good to hear that you solved the issue. In the previous comment, I just want to make sure that you can login to SQL Management Studio using Quicksilver account, and access Commerce databases :)
