### ISSUE TITLE
Implement FindSearchProvider for QuickSilver

### ISSUE THREAD

**Issue by madu255** [episerver/Quicksilver#44]
Hi Commerce Team,

I notice that the QuickSilver B2B solution already utilized FindSearchProvider. Could you also update QuickSilver solution to allow using FindSearchProvider instead of LuceneSearchProvider?

Dzung Le - EPiServer Application Support Team

**Comment by namserious** [comment]
Hi Dzung,

Quicksilver is just a sample, we're able to modify the Search Provider. If you would like to use FindSearchProvider, you can follow this documentation https://world.episerver.com/documentation/developer-guides/commerce/search/Configuring-Episerver-Find-search-provider/ 

Cheers,

**Comment by madu255** [comment]
The above documentation doesn't help. The search function of QuickSilver is not implemented with Find's libraries, no result is returned.

![quicksilver-search-function](https://user-images.githubusercontent.com/15663764/67199593-dc66b380-f42b-11e9-9655-b6b993740764.PNG)

Plus, the following code doesn't allow using any search provider other than LuceneSearchProvider. The result is returned as SearchProviderType.Unknown.

![quicksilver-LoadSearchProvider PNG](https://user-images.githubusercontent.com/15663764/67199660-0029f980-f42c-11e9-8427-e563183b9847.png)
