### ISSUE TITLE
Wrong .gitignore file

### ISSUE THREAD

**Issue by kaspars-ozols** [episerver/Quicksilver#5]
Line containing "Sources/EPiServer.Reference.Commerce.Manager/App_GlobalResources/*" should be removed from .gitignore file as referenced folder contains important source files thet needs to be tracked

**Comment by quanmaiepi** [comment]
Hi,
My bad - read it too fast. We'll look into this issue. Thanks for your input.

**Comment by quanmaiepi** [comment]
We pushed a new change which removes that line from .gitinore.
Thanks.
