### ISSUE TITLE
Intermediate build files removed after building

### ISSUE THREAD

**Issue by alexanderchr** [episerver/Quicksilver#6]
The intermediate build files are removed after each build forcing us to rebuild the project from scratch. Is this required or may the build task responsible for the removal be safely removed?

https://github.com/episerver/Quicksilver/blob/master/Sources/EPiServer.Reference.Commerce.Site/EPiServer.Reference.Commerce.Site.csproj#L1023

**Comment by quanmaiepi** [comment]
It should be safe to remove the target. I think the purpose was to create a clean folder for publishing to Github. We'll see if we can remove that in upcoming commits.

**Comment by alexanderchr** [comment]
Cool. Thanks for the immediate response. Speed up our builds by 5x.
