### ISSUE TITLE
Create new CMS and Commerece User

### ISSUE THREAD

**Issue by jon419** [episerver/Quicksilver#8]
When I create a user in the CMS Admin and assign them to all the appropriate roles, they are unable to log into the CMS and Commerce Manager.

**Comment by quanmaiepi** [comment]
Hi,
See the comment in the other issue. You might want to check out our develop branch (1.2) to see if it works for you.

**Comment by jon419** [comment]
So is the solution to eliminate the membership and role providers in the web.config?  How would one go about adding and removing CMS users when you are using the identity framework without some form of remote ldap or federated services?

**Comment by lunchin** [comment]
This is something that has to be fixed in admin mode and is on the backlog to be able to manage users from different authentication schemes.  You can use this blog post for a temporary solution until it is fixed in cms.

http://sveinaandahl.blogspot.no/2015/08/admin-tool-for-aspnet-identity.html

http://sveinaandahl.blogspot.no/2015/11/how-to-fix-roles-in-episerver-when.html

**Comment by Hyzac** [comment]
Having applied the fixes from Svein, changing the UserValidator and PasswordValidator in ApplicationUserManager, and adding a email-address to the admin user I was able to successfully change/create users and change password on admin user. What I'm struggling with is giving new users access to the Commerce manager UI. Is this possible with the Identity setup or is the admin user the only user that have access to this? I can se created users under Contacts in CommerceManager but the Roles part of the management states it is obsolete.

**Comment by magnusstrale** [comment]
This is being worked on. As soon as the proper support exists in the base packages we will update Quicksilver accordingly. See http://world.episerver.com/support/Bug-list/bug/COM-1553

**Comment by frederikvig** [comment]
@magnusstrale COM-1553 doesn't exist. Is there a different bug ID?

**Comment by quanmaiepi** [comment]
It's not yet visible. We are still working on that

**Comment by Drol** [comment]
Any progress on this?

In CMS OWIN Startup we have implemented EPiServer.CMS.UI.AspNetIdentity using app.AddCmsAspNetIdentity<ApplicationUser>();

But how can we give access to commerce manager to users created using CMS Admin page? If I don't miss anything obvious CM is authentication from the Commerce DB and not the CMS DB in Quicksilver. Correct?

**Comment by lunchin** [comment]
We are working on this to use the new cms package.  However the the connection should be set by ApplicationUser class.  Does not matter which database host the tables as long as both sites use the same ApplicationUser

**Comment by Drol** [comment]
Thanks @lunchin. I feel kinda stupid now :-D

To anyone else it is not ApplicationUser class. It is in ApplicationDbContext.

`public ApplicationDbContext()
            : base("EPiServerDB", throwIfV1Schema: false)
        {
        }`

**Comment by mclausing** [comment]
Is there any update on this? I see several related issues have been closed and there are comments that make it seem as if it has can be implemented, but no change on the status.

I see there is a change to startup.cs to use AddCmsAspNetIdentity which provides proper authentication, but not the authorization needed to access CommerceManager. As configured, Commerce Manager authorization requires an entry in aspnet_UserInRoles and an update to the ApplicationID for ECApplication in aspnet_Users. As it stands now, aspnet_Users are created using the default Application of "/".

**Comment by mclausing** [comment]
Actually, it looks like the virtualRoles node is either missing from Commerce Manager web.config or the EPiServerFramework.config should be used instead. I was having trouble getting it to work on one of our projects and had been referencing Quicksilver, which doesn't appear to be working correctly.

**Comment by quanmaiepi** [comment]
I'm working on this exact bug, and if you are using the AspNetIdentity (which is default in Quicksilver), make sure to remove all membership/role providers in Commerce Manager web.config. I.e. it should look like this

`    <roleManager>
      <providers>
        <clear />
      </providers>
    </roleManager>
    <membership>
      <providers>
        <clear />
      </providers>`

**Comment by tienquachs60** [comment]
We encountered the same issue even on the latest version of QuickSilver. Quan is correct. It only work  if we disable the roleManager in Commerce Manager
<roleManager enabled="false"> <providers> <clear /> </providers> </roleManager> 

Hope this help.
