### ISSUE TITLE
Change in ServiceInstanceScope for PromotionService/EntryService/HelperFacade throws error when sessionstate is enabled

### ISSUE THREAD

**Issue by jstemerdink** [episerver/Quicksilver#9]
After the change of the ServiceInstanceScope from Singleton to HybridHttpSession on PromotionService/EntryService/HelperFacade (in the development branche), Redis throws an error that these are not marked Serializable.

When marking them Serializable:
PromotionHelper in Facade must be marked NonSerialized, as is it not serializable.
ReferenceConverter in PromotionService must be marked NonSerialized, as is it not serializable.

**Comment by mrahl** [comment]
Thanks for reporting, sorry for the late reply. I have logged this bug in our internal repo and we will look into it shortly.

**Comment by vimvq1987** [comment]
Hi,
It should be fixed by now  with latest commit in develop.

**Comment by quanmaiepi** [comment]
Hi,
It should be fixed by now with latest commit in develop. The life cycle has been changed back to Singleton

**Comment by mrahl** [comment]
Right you are, I should have checked first. The code is the same in master too.

**Comment by magnusstrale** [comment]
Closing
